version: 1

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s: %(module)s.%(funcName)s +%(lineno)d %(message)s"
    datefmt: "%H:%M:%S"

  extended:
    format: "%(asctime)s - %(name)s - %(levelname)s: %(module)s.%(funcName)s +%(lineno)d %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: extended
    filename: "logs.txt"
    mode: "w"

loggers:
  consoleLogger:
    level: INFO
    handlers: [console]
    propagate: no

  fileLogger:
    level: DEBUG
    handlers: [file]
    propagate: no

  fullLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  handlers: [file]